qbittorrent:
  image: linuxserver/qbittorrent:4.5.1
  downloads_folder:
    size: 15Gi
  config_folder:
    size: 3Gi
  host: toto
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 250m
      memory: 150Mi
  middlewares: []

  secrets: {}

plex:
  image: linuxserver/plex:1.30.2
  config_folder:
    size: 10Gi
  host: toto
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 250m
      memory: 250Mi
  middlewares: []

  secrets:
    PLEX_CLAIM: ""
