apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: plex-qbittorrent
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: plex-qbittorrent
  template:
    metadata:
      labels:
        app: plex-qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: {{ .Values.qbittorrent.image }}
          imagePullPolicy: Always
          resources:
            requests:
            {{- range $k, $v := .Values.qbittorrent.resources.requests }}
              {{ $k }}: {{ $v }}
            {{- end }}
            limits:
            {{- range $k, $v := .Values.qbittorrent.resources.limits }}
              {{ $k }}: {{ $v }}
            {{- end }}
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-config
            - mountPath: /downloads
              name: qbittorrent-downloads
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-qbittorrent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        - name: plex
          image: {{ .Values.plex.image }}
          imagePullPolicy: Always
          resources:
            requests:
            {{- range $k, $v := .Values.plex.resources.requests }}
              {{ $k }}: {{ $v }}
            {{- end }}
            limits:
            {{- range $k, $v := .Values.plex.resources.limits }}
              {{ $k }}: {{ $v }}
            {{- end }}
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /media
              name: qbittorrent-downloads
          ports:
            - name: tcp-plex
              containerPort: 32400
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-plex
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-qbittorrent-config
        - name: plex-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plex-config
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-qbittorrent-downloads
