apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plex
  labels:
    app: plex-qbittorrent
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: plex-qbittorrent
  ports:
    - name: http
      port: 32400
      targetPort: tcp-plex
      protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-plex
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.plex.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-plex
          port: 32400
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-plex
spec:
  entryPoints:
    - plex
  routes:
    - match: HostSNI(`{{ required "A valid plex host is required!" .Values.plex.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-plex
          port: 32400
      {{- if .Values.qbittorrent.middlewares }}
      middlewares:
      {{- range $v := .Values.qbittorrent.middlewares }}
        - name: {{ $v }}
      {{- end }}
      {{- end }}
  tls:
    certResolver: letsencrypt
